### ISSUE TITLE
what is the the purpose of of  label_predicates?

### ISSUE THREAD

**Issue by sunke-github** [IBCNServices/KGPTree#2]
Could you please give explaiton of the following question.
if p not in label_predicates:
       s = str(s)
       p = str(p)
       o = str(o)
Why you remove the predicates that in label_predicates? and where does the label_predicates come from?

**Comment by GillesVandewiele** [comment]
Hi @sunke-github 

There's 2 reasons that come to mind why one would want to use `label_predicates`:
1. To filter out triples that carry little meaning. An example would be that each DBpedia page has a `dbo:wikiPageID`. These carry little information for any further downstream ML task and will only introduce noise. So adding `dbo:wikiPageID` to label_predicates could improve the quality of the embeddings. This is more relevant to RDF2Vec than to MINDWALC, as the information gain for walks including these predicates will be very low anyway and will therefore not be selected. It can, however, speed up the walk mining procedure.

2. There are some benchmark datasets out there where the ground truth is present within the KG itself. Of course, if we would not exclude this ground truth, the accuracy would be perfect (100%). Therefore we filter out this ground truth with label-predicates. An example is the MUTAG benchmark dataset where the `isMutagenic` label which we are trying to classify is available in the KG itself.
