### ISSUE TITLE
plot the decision tree of a trained MINDWALCTree

### ISSUE THREAD

**Issue by MaxLegnar** [IBCNServices/KGPTree#5]
Dear developers of MINDWALC,

first of all, thank you so much for sharing this project and the Paper with the world.
I was wondering if there is already a function in your project that can be used to plot the decision tree of a trained MINDWALCTree. If not: Do you have any suggestions how i could do that in a simple way?

Thank you and best regards:
Max

**Comment by GillesVandewiele** [comment]
Hi Max,

Thank you for showing interest in MINDWALC! The Decision Tree class in this repo is an adapted version of the one in GENESIM. You could use the visualisation function in there with some adaptations. This uses graphviz however, and the walks might perhaps be too long to plot nicely

For the decision trees in our paper, I made them by hand in draw.io by inspecting the tree object.

https://github.com/IBCNServices/GENESIM/blob/master/decisiontree.py#L202

**Comment by MaxLegnar** [comment]
Hi Gilles,

thank you for your tip. It was very helpful. If anyone is interested: This is my solution:

in datastructures.py:
# ...
from graphviz import Source

class Tree():
    # ...

    def visualise(self, output_path, _view=True):
        """Visualise the tree with [graphviz](http://www.graphviz.org/),
         using `decisiontree.DecisionTree.convert_to_dot`
        **Params**
        ----------
          - `output_path` (string) - where the file needs to be saved
          - `_view` (boolean) - open the pdf after generation or not
        **Returns**
        -----------
            a pdf with the rendered dot code of the tree
        """
        src = Source(self.convert_to_dot())
        src.render(output_path, view=_view)

    def convert_to_dot(self):
        """Converts a decision tree object to DOT code
        **Params**
        ----------
          - ...
        **Returns**
        -----------
            a string with the dot code for the decision tree
        """
        s = 'digraph DT{\n'
        s += 'node[fontname="Arial"];\n'
        s += self._convert_node_to_dot()
        s += '}'
        return s

    def _convert_node_to_dot(self, count=1):
        """Convert node to dot format in order to visualize our tree using graphviz
        :param count: parameter used to give nodes unique names
        :return: intermediate string of the tree in dot format, without preamble (this is no correct dot format yet!)
        """
        if self._class is not None:  # leaf node:
            label = self._class
            s = 'Node' + str(count) + ' [label="' + str(label) + '" shape="box"];\n'
        else:  # decision node:
            label = f'{self.walk[0]} (d = {self.walk[1]})'
            s = 'Node' + str(count) + ' [label="' + f'{label}' + '"];\n'
            s += self.left._convert_node_to_dot(count=count + 1)
            s += 'Node' + str(count) + ' -> ' + 'Node' + str(count + 1) + ' [label="false"];\n'
            amount_subnodes_left = self.left.node_count
            s += self.right._convert_node_to_dot(count=count + amount_subnodes_left + 1)
            s += 'Node' + str(count) + ' -> ' + 'Node' + str(count + amount_subnodes_left + 1) + ' [label="true"];\n'

        return s

**Comment by GillesVandewiele** [comment]
Great to hear! If you create a PR, I'll be happy to merge this in :). Closing the issue as it seems fixed.
